### ISSUE TITLE
How to change Icon

### ISSUE THREAD

**Issue by Vincent30Str** [voidlhf/StarRailGrubThemes#5]
Hi excuse me, can i ask how to change the os icon from windows 10 to windows 11?

**Comment by voidlhf** [comment]
Delete the 'windows.png' file under the 'icons' folder, and then rename the file 'windows11.png' to 'windows.png'.

**Comment by Vincent30Str** [comment]
it works. thanks. also, may i ask, is it possible to change grub's font?

**Comment by voidlhf** [comment]
I'm sorry, this theme currently does not support custom fonts.
